[package]
name = "dag"
version = "0.1.0"
edition = "2021"

[dependencies]
core = { path = "../../core" }
network = { path = "../../network" }
compute = { path = "../../compute" }
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }
sugars = "3.0.0"
